horizontal
cpu_stats
cpu_mhz
gpu_stats
fps
frametime
frame_timing=0
font_size=18
background_alpha=0.3
position=top-left


output_folder=/home/sepi4/mangologs
log_duration=0
autostart_log=0
toggle_logging=Shift_L+F2
log_interval=100