# # Font settings
font_family      JetBrains Mono Light
font_size        13

# window_padding_width 4
window_margin_width 4
# foreground #dddddd
# background #1F1F1F

linux_display_server x11

cursor_blink_interval 0

# ctrl+shift+f5


# BEGIN_KITTY_THEME
# VSCode_Dark
include current-theme.conf
# END_KITTY_THEME