# ctrl+shift+f5 # RELOAD CONFIG
# 
# # Font settings
font_family        JetBrainsMono Nerd Font
# font_size        13
font_size        11.5

# window_padding_width 4
window_margin_width 4
# foreground #dddddd
# background #1F1F1F

linux_display_server x11

cursor_blink_interval 0



# BEGIN_KITTY_THEME
# 3024 Night
include current-theme.conf
# END_KITTY_THEME
