#!/bin/bash

videos=""
for file in $PWD/*
do
    videos+="file '$file'\n"
done
echo -e $videos > /tmp/merge.txt

if [ $1 ]
then
    ffmpeg -f concat -safe 0 -i /tmp/merge.txt -c copy $1
else
    ffmpeg -f concat -safe 0 -i /tmp/merge.txt -c copy output.mp4
fi
